### ISSUE TITLE
Deploying Sample Ruby on Rails App Fails When Using ror-container Image

### ISSUE THREAD

**Issue by danielhelfand** [sclorg/ror-container#37]
I have added the `ror-container` image via an [imagestream](https://gist.github.com/danielhelfand/9bf7380614f4ac9a4681f465131f2348) to an OpenShift 3.11 catalog and attempted to deploy a sample Ruby on Rails application. When deploying to the application to OpenShift via the option in the catalog, I get the following message in the logs after the build fails:

```
warning: Image sha256:65bdb4dedee0b67f87cb047a939b091bc9a3b330895647c61cd42f285b3577d0 does not contain a value for the io.openshift.s2i.scripts-url label
```

The `ror-container` image used was `CentOS 7` with Ruby on Rails version 5.0.

**Comment by danielhelfand** [comment]
I hadn't realized the `ror-container` isn't `s2i` enabled. This is the reason for the error above.

**Comment by pvalena** [comment]
That's correct. You can still use it as non-s2i container (mount something inside?) though.

For generic Rails application (with additional dependencies) please use [s2i-ruby-container](https://github.com/sclorg/s2i-ruby-container).
